version: 0.1

phases:
  install:
    run-as: root
    commands:
      - make install
  pre_build:
    commands:
      - g++ --version
      - clang++ --version
      - icpc --version
  build:
    commands:
      - make
      - make test

