version: 0.2

phases:
  install:
    run-as: root
    commands:
      - make install
  pre_build:
    commands:
      - g++ --version
      - clang++ --version
      # - icpc --version # Intel CC on build machine expired...
  build:
    commands:
      - make
      - make test

